language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-3.4.2
    - android-28
before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x ./gradlew
  - touch local.properties
script:
  - ./gradlew build connectedCheck