language: android

env:
  matrix:
    - ANDROID_TARGET=android-28  ANDROID_ABI=armeabi-v7a


android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-3.4.2
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_TARGET

before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x ./gradlew
  - touch local.properties

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - ./gradlew build connectedCheck
  - ./gradlew connectedAndroidTest